version: 0.2
phases:
  install:
    run-as: root
    commands:
      - echo install phases
      - apt-get update -y && apt-get install -y nginx 
  pre_build:
    run-as: root
    commands:
      - echo nothing to do in prebuild
      - service nginx start
  build:
    run-as: root
    commands:
      - echo build stage
      - cd /usr/share/nginx/html && rm -rf index.html
      - cp -R /css /fonts /img /scripts /appspec.yml /buildspec.yml /index.html /LICENSE /README.md /usr/share/nginx/html
  post_build:
    commands:
      - echo nothing to do in post build.

