version: 0.2
phases:
  install:
    run-as: root
    commands:
      - echo install phases
      - apt-get update -y && apt-get install -y docker && apt-get install -y docker.io
  pre_build:
    run-as: root
    commands:
      - echo nothing to do in prebuild
      - systemctl start docker.service
  build:
    run-as: root
    commands:
      - echo build stage
      - docker pull nginx && mkdir gnani
      - cp -R /css /fonts /img /scripts /appspec.yml /buildspec.yml /index.html /LICENSE /README.md /home/ubuntu/gnani
      - docker run --name webserver -p 80:80 -v /home/ubuntu/gnani:/usr/share/nginx/html -d nginx
  post_build:
    commands:
      - echo nothing to do in post build.

