version: 0.2
phases:
  install:
    run-as: root
    commands:
      - echo install phases
      - apt install docker 
      - systemctl start docker.service
      - usermod -aG docker ubuntu
  pre_build:
    commands:
      - echo nothing to do in prebuild
  build:
    run-as: root
    commands:
      - echo build stage
      - docker pull nginx && mkdir gnani
      - cp -R ./* /home/ubuntu/gnani 
      - docker run --name webserver -p 80:80 -v /home/ubuntu/gnani:/usr/share/nginx/html -d nginx
  post_build:
    commands:
      - echo nothing to do in post build.

